import { ImageSourcePropType } from "react-native";

export const imageLoader: { [name: string]: ImageSourcePropType } = {
  catalunya: require("../assets/images/catalunya/catalunya-f1.webp"),
  hungaroring: require("../assets/images/hungaroring/hungaroring-f1.webp"),
  imola: require("../assets/images/imola/imola-f1.webp"),
  jeddah: require("../assets/images/jeddah/jeddah-f1.webp"),
  melbourne: require("../assets/images/melbourne/melbourne-f1.webp"),
  miami: require("../assets/images/miami/miami-f1.webp"),
  montecarlo: require("../assets/images/monte-carlo/monte-carlo-f1.webp"),
  montreal: require("../assets/images/montreal/montreal-f1.webp"),
  sakhir: require("../assets/images/sakhir/sakhir-f1.webp"),
  shanghai: require("../assets/images/shanghai/shanghai-f1.webp"),
  silverstone: require("../assets/images/silverstone/silverstone-f1.webp"),
  spafrancorchamps: require("../assets/images/spa/spa-f1.webp"),
  spielberg: require("../assets/images/spielberg/spielberg-f1.webp"),
  suzuka: require("../assets/images/suzuka/suzuka-f1.webp"),
  zandvoort: require("../assets/images/zandvoort/zandvoort-f1.webp"),
  monza: require("../assets/images/monza/monza-f1.webp"),
  baku: require("../assets/images/baku/baku-f1.webp"),
  singapore: require("../assets/images/singapore/singapore-f1.webp"),
  austin: require("../assets/images/austin/austin-f1.webp"),
  mexicocity: require("../assets/images/mexicocity/mexicocity-f1.webp"),
  interlagos: require("../assets/images/interlagos/interlagos-f1.webp"),
  lasvegas: require("../assets/images/lasvegas/lasvegas-f1.webp"),
  lusail: require("../assets/images/lusail/lusail-f1.webp"),
  yasmarinacircuit: require("../assets/images/yasmarinacircuit/yasmarinacircuit-f1.webp"),
  alternative: require("../assets/images/alternative/alternative-f1.webp"),
};
